apiVersion: v1
kind: Service
metadata:
  name: {{ include "echoserver.fullname" . }}
  labels:
    {{- include "echoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5980
      protocol: TCP
      name: tcp
  selector:
    {{- include "echoserver.selectorLabels" . | nindent 4 }}
